# Generated by Django 5.0.14 on 2026-07-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Лимит', 'verbose_name_plural': 'Лимиты'},
        ),
    ]
